////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ServerPackets
{
    [PacketHeader("ps_op")]
    public class PsopPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public byte PetId { get; set; }
        [PacketIndex(1)]
        public byte SkillSlot { get; set; }

        [PacketIndex(2)]
        public byte Option { get; set; }
        #endregion
    }
}